function contab = makePrlCont(mpc, esc)
%makePrlCont: Create gencost steps for price-responsive load in contingency hours

% E4ST
% Copyright (c) 2012-2022 by Power System Engineering Research Center (PSERC)
% by Biao Mao (Rensselaer Polytechnic Institute) and Paul Picciano (Resources for the Future)
%
% This file is part of E4ST.
% Covered by the 3-clause BSD License (see LICENSE file for details).

global verbose % Display Progress Information

nh = size(esc.hrs_map, 1); % Total hours (including base hours)
iDl = find(strcmp(mpc.genfuel, 'dl'));
nDl = length(iDl);
probability = esc.hrs_map{:, 'probability'};

% The rows generated by 'dl' is nDl * 18 * (nHours - 1);
% 10 steps of pairs; last two are zero
nConts = nDl * 18 * (nh - 1); % total rows in contab
contab = zeros(nConts, 7);

% Save the original mpc for scaling
for i = 2:nh
    gencost = makePrlStep(mpc, esc, i);
    iCont = i - 1;

    % Create contab for one hour
    col2Change = 1:22; % Columns need to be changed
    nCol = length(col2Change); % Total columns
    nSigCont = nDl * nCol; % Total rows of contabs for one hour
    gencostVec = reshape(gencost(:, col2Change), [], 1); % Value need to be changed
    headVec1 = repmat([iCont, probability(i), 9], nSigCont, 1); % 9 specifies apply_changes to modify gencost table
    headVec2 = repmat(iDl, nCol, 1);
    headVec3 = reshape(repmat(col2Change, nDl, 1), [], 1); % Column id to change
    headVec4 = repmat([1], nSigCont, 1);
    contab1 = [headVec1, headVec2, headVec3, headVec4, gencostVec];
    contab(1+(iCont - 1)*nSigCont:iCont*nSigCont, :) = contab1;
end
